export default [
  {
    id: 1,
    name: 'Куртка из двух материалов',
    category: 'jacket',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['#42aaff'],
    price: 2500,
    comment: [],
    img: ['kurtka-iz-dvukh-materialov-goluboj-muzhchiny-s-xxl-xp331_1_lpr1.webp', 'kurtka-iz-dvukh-materialov-goluboj-muzhchiny-s-xxl-xp331_1_lpr2.webp', 'kurtka-iz-dvukh-materialov-goluboj-muzhchiny-s-xxl-xp331_1_lpr3.webp'],
  },
  {
    id: 2,
    name: 'Парка с капюшоном в стиле пуховика',
    category: 'jacket',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['#806b2a'],
    price: 3700,
    comment: [],
    img: ['parka-s-kapyushonom-v-stile-pukhovika-khaki-muzhchiny-s-xxl-xp340_3_lpr2.webp', 'parka-s-kapyushonom-v-stile-pukhovika-khaki-muzhchiny-s-xxl-xp340_3_frf5.webp', 'parka-s-kapyushonom-v-stile-pukhovika-khaki-muzhchiny-s-xxl-xp340_3_frf3.webp'],
  },
  {
    id: 3,
    name: 'Джинсовая куртка',
    category: 'jacket',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['#808080'],
    price: 1700,
    comment: [],
    img: ['dzhinsovaya-kurtka-seryj-muzhchiny-s-xxl-xd216_1_frf1.webp', 'dzhinsovaya-kurtka-seryj-muzhchiny-s-xxl-xd216_1_frf6.webp', 'dzhinsovaya-kurtka-seryj-muzhchiny-s-xxl-xd216_1_frm.webp'],
  },
  {
    id: 4,
    name: 'Куртка из твила на основе хлопка',
    category: 'jacket',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['#42aaff'],
    price: 1200,
    comment: [],
    img: ['kurtka-iz-tvila-na-osnove-khlopka-goluboj-muzhchiny-s-xxl-xg714_1_frf1.webp', 'kurtka-iz-tvila-na-osnove-khlopka-goluboj-muzhchiny-s-xxl-xg714_1_frf3.webp', 'kurtka-iz-tvila-na-osnove-khlopka-goluboj-muzhchiny-s-xxl-xg714_1_frf6.webp'],
  },
  {
    id: 5,
    name: 'Облегающие джинсы из хлопка',
    category: 'jeans',
    size: [42, 44, 46, 48, 50, 52],
    color: ['white'],
    price: 1300,
    comment: [],
    img: ['oblegayushie-dzhinsy-iz-khlopka-belyj-muzhchiny-s-xxl-vr686_13_frf1.webp', 'oblegayushie-dzhinsy-iz-khlopka-belyj-muzhchiny-s-xxl-vr686_13_frf5.webp'],
  },
  {
    id: 6,
    name: 'Узкие джинсы с выбеленным эффектом',
    category: 'jeans',
    size: [42, 44, 46, 48, 50, 52],
    color: ['#42aaff'],
    price: 2100,
    comment: [],
    img: ['uzkie-dzhinsy-s-vybelennym-effektom-goluboj-muzhchiny-s-xxl-xg462_1_frf1.webp', 'uzkie-dzhinsy-s-vybelennym-effektom-goluboj-muzhchiny-s-xxl-xg462_1_frf2.webp'],
  },
  {
    id: 7,
    name: 'Джинсы стандартного кроя',
    category: 'jeans',
    size: [42, 44, 46, 48, 50, 52],
    color: ['#808080'],
    price: 2100,
    comment: [],
    img: ['dzhinsy-standartnogo-kroya-goluboj-muzhchiny-s-xxl-xq041_3_frf1.webp', 'dzhinsy-standartnogo-kroya-goluboj-muzhchiny-s-xxl-xq041_3_frf2.webp', 'dzhinsy-standartnogo-kroya-goluboj-muzhchiny-s-xxl-xq041_3_frf3.webp'],
  },
  {
    id: 8,
    name: 'Зауженные джинсы из эластичного хлопка L32',
    category: 'jeans',
    size: [58, 60, 62, 64, 66, 68],
    color: ['##4b0082'],
    price: 1700,
    comment: [],
    img: ['zauzhennye-dzhinsy-iz-elastichnogo-khlopka-l32-sinij-indigo-muzhchiny-bolshie-razmery-wp147_1_frf1.webp', 'zauzhennye-dzhinsy-iz-elastichnogo-khlopka-l32-sinij-indigo-muzhchiny-bolshie-razmery-wp147_1_frf3.webp'],
  },
  {
    id: 9,
    name: 'Футболка Eco-conception c флагом',
    category: 'undershirt',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['white'],
    price: 500,
    comment: [],
    img: ['futbolka-eco-conception-c-flagom-belyj-muzhchiny-s-xxl-xo531_2_frf1.webp', 'futbolka-eco-conception-c-flagom-belyj-muzhchiny-s-xxl-xo531_2_frf4.webp'],
  },
  {
    id: 10,
    name: 'Текстурная футболка Eco-conception',
    category: 'undershirt',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['#c93c20'],
    price: 700,
    comment: [],
    img: ['futbolka-eco-conception-serfer-krasnyj-muzhchiny-s-xxl-xo531_12_frf1.webp', 'futbolka-eco-conception-serfer-krasnyj-muzhchiny-s-xxl-xo531_12_frf3.webp'],
  },
  {
    id: 11,
    name: "Футболка Eco-conception 'The Boss'",
    category: 'undershirt',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['white'],
    price: 350,
    comment: [],
    img: ['futbolka-eco-conception-the-boss-belyj-muzhchiny-s-xxl-xt255_8_frf1.webp', 'futbolka-eco-conception-the-boss-belyj-muzhchiny-s-xxl-xt255_8_frf2.webp'],
  },
  {
    id: 12,
    name: "Футболка Eco-conception 'Ворчун'",
    category: 'undershirt',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['#42aaff'],
    price: 350,
    comment: [],
    img: ['futbolka-eco-conception-vorchun-goluboj-muzhchiny-s-xxl-xt255_6_frf1.webp', 'futbolka-eco-conception-vorchun-goluboj-muzhchiny-s-xxl-xt255_6_frf3.webp'],
  },
  {
    id: 13,
    name: 'Спортивные шорты из мольтона',
    category: 'sport',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['#black'],
    price: 990,
    comment: [],
    img: ['sportivnye-shorty-iz-moltona-chernyj-muzhchiny-s-xxl-xg609_1_frf1.webp', 'sportivnye-shorty-iz-moltona-chernyj-muzhchiny-s-xxl-xg609_1_frf2.webp', 'sportivnye-shorty-iz-moltona-chernyj-muzhchiny-s-xxl-xg609_1_frf3.webp', 'sportivnye-shorty-iz-moltona-chernyj-muzhchiny-s-xxl-xg609_1_frf6.webp'],
  },
  {
    id: 14,
    name: 'Спортивное трико',
    category: 'sport',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['#black'],
    price: 1500,
    comment: [],
    img: ['sportivnye-bryuki-chernyj-muzhchiny-s-xxl-xp909_2_frf1.webp', 'sportivnye-bryuki-chernyj-muzhchiny-s-xxl-xp909_2_frf2.webp'],
  },
  {
    id: 15,
    name: "Ветровка колор-блок 'Eco-conception'",
    category: 'sport',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['#42aaff'],
    price: 2000,
    comment: [],
    img: ['vetrovka-kolor-blok-eco-conception-goluboj-muzhchiny-s-xxl-xg165_1_frf4.webp', 'vetrovka-kolor-blok-eco-conception-goluboj-muzhchiny-s-xxl-xg165_1_frf5.webp', 'vetrovka-kolor-blok-eco-conception-goluboj-muzhchiny-s-xxl-xg165_1_frf1.webp'],
  },

];
